### ISSUE TITLE
R-7 fins

### ISSUE THREAD

**Issue by biohazard15** [friznit/Unofficial-Tantares-Wiki#14]
All R-7 family rockets are shown with Canopus Basic Fin B, while building manual states that you need to use Canopus Basic Fin A.

**Comment by friznit** [comment]
But which one is correct?

**Comment by biohazard15** [comment]
I think Type B is the correct one. Here's a good example (this one is Soyuz 11A511 installed in Samara):
![0026](https://user-images.githubusercontent.com/62663094/101225384-be4d2880-36aa-11eb-8f8f-dbbed9e80f10.jpg)

**Comment by friznit** [comment]
Good!  That's an easy fix then :)
