### ISSUE TITLE
Guide missing in ISS - Mir

### ISSUE THREAD

**Issue by MatiasBD1** [friznit/Unofficial-Tantares-Wiki#17]
Hello!
With all due respect, this wiki is great, but it's just not your BDB wiki. You seem to be the only person I've found that really knows how to assemble the Tantares craft accurately, but at least on the more detailed craft, like ISS or Mir modules, it seems you just attached graphs to the wiki pages, which, in my opinion, makes it a bit more confusing than it really is.
I'd appreciate if you could show how to assemble the ISS-Mir Zvezda and Zarya modules. I know this might sound a bit like "yo you lazy wake up and tell me how to do this bitch", but it isn't. I'm just a bit confused by this and am asking for help. 
-Matias

**Comment by friznit** [comment]
It's a fair comment and I agree it's a bit lazy.  I'll get that fixed.

For the record, my build guides are based on Beale's vision of how his parts are meant to go together combined with some poking around at whatever imagery I can find on the interwebs plus or minus a little bit of artistic license to keep it Kerbal.

**Comment by friznit** [comment]
I've added a basic build guide for the ISS modules.  Hope that helps!
