### ISSUE TITLE
ISS

### ISSUE THREAD

**Issue by Pappystein** [friznit/Unofficial-Tantares-Wiki#19]
Two things, one I think is easy and the other may be pretty hard...

1) EASY ONE:    Please have a link in each of the two ISS articles linking between each other.   Prevents the user from having to go to the KSP forums to find your signature on one of your posts to find the "other half" of the instructions.

2)  github.com dark mode compatibility (pictures with white backgrounds and black text have un-readable text in dark mode because black on black....    If there is a way to fix this that would be awesome for those of us who have big video walls or large monitors and are light sensitive.

**Comment by friznit** [comment]
1. Done
2. I know, there's already a ticket on the BDB wiki - I'm going to have to redo every image, which may take some time.

**Comment by Pappystein** [comment]
Awesome!  thanks for creating the Link!
