### ISSUE TITLE
More instruction

### ISSUE THREAD

**Issue by KazBodnar** [friznit/Unofficial-Tantares-Wiki#7]
You should add building instructions for **all** the craft (especially the LK lander and the N1 payload/L3)

**Comment by friznit** [comment]
Thanks for the reminder!  N1 and some other pages are still work in progress.

**Comment by KazBodnar** [comment]
Thanks! Nice job on the wiki. I would also like to see instructions on how to build the crewed craft (such as Soyuz, etc.) and space stations. Anyway, keep up the good work.

**Comment by friznit** [comment]
N1-L3 and Crew Modules pages have been updated.  Still have to finish the space stations!
